# Generated by Django 2.0.1 on 2018-01-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('story_title', models.CharField(max_length=500)),
                ('story_content', models.TextField()),
                ('story_rating', models.IntegerField(max_length=1)),
            ],
        ),
    ]
