# Generated by Django 2.0.1 on 2018-01-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_rating',
            field=models.IntegerField(),
        ),
    ]
