# Generated by Django 2.0.1 on 2018-01-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='story_id',
            new_name='story',
        ),
    ]
