# Generated by Django 2.0.1 on 2018-01-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20180124_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_rating',
        ),
    ]
